### ISSUE TITLE
Error starting loopback with loopback-component-model-diagram

### ISSUE THREAD

**Issue by gerbenbas** [redbabel/loopback-component-model-diagram#3]
I installed loopback-component-model-diagram@0.3.0 with strongloop 6.0.3 and node 4.2.6 at Ubuntu 16.10 (kernel 4.8.0-34-generic). When I define the mountpath in component-config.json and run loopback, I get the following error:

LOOPBACK_FOLDER/node_modules/loopback-component-model-diagram/lib/diagram/index.js:3
let nomnomlSource = '';
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (LOOPBACK_FOLDER/node_modules/loopback-component-model-diagram/lib/routes.js:2:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (LOOPBACK_FOLDER/node_modules/loopback-component-model-diagram/lib/index.js:3:16)
    at Module._compile (module.js:410:26)

**Comment by alemhnan** [comment]
From version 0.3.0 the component requires node 6.0 or higher. If you upgrade to node 6.x.x you should be fine.

Although I got few people with the same problem. Since it's not strictly required node 6 for the component to work I'm thinking to reintroduce compatibility to node 4.x.x.

**Comment by alemhnan** [comment]
Closing for now.
